### ISSUE TITLE
Does image build include installing security updates?

### ISSUE THREAD

**Issue by t4nguy3n** [nginx/docker-nginx-unprivileged#174]
May I know if the image build and releases include installing security updates for example `sudo apt list --upgradable | grep security |cut -d\/ -f1|xargs sudo apt-get install -y`?

**Comment by alessfg** [comment]
Hey @t4nguy3n! 

The short answer is that it does not. The images get rebuilt once a week and for the most part any potential/confirmed CVEs with *a* fix are fixed within the week if not earlier. You can always extend this image and add an extra RUN command if you want!
